import { d, state } from "./util.js";

// Uttar Pradesh — 75 districts (real). City defaults to the district HQ; a few
// districts whose principal city differs from the district name list it.
export const uttarPradesh = state("UP", "Uttar Pradesh", [
  d("Agra"),
  d("Aligarh"),
  d("Ambedkar Nagar", "Akbarpur"),
  d("Amethi", "Gauriganj"),
  d("Amroha"),
  d("Auraiya"),
  d("Ayodhya", "Ayodhya", "Faizabad"),
  d("Azamgarh"),
  d("Baghpat"),
  d("Bahraich"),
  d("Ballia"),
  d("Balrampur"),
  d("Banda"),
  d("Barabanki"),
  d("Bareilly"),
  d("Basti"),
  d("Bhadohi", "Gyanpur"),
  d("Bijnor"),
  d("Budaun"),
  d("Bulandshahr"),
  d("Chandauli"),
  d("Chitrakoot", "Karwi"),
  d("Deoria"),
  d("Etah"),
  d("Etawah"),
  d("Farrukhabad", "Fatehgarh"),
  d("Fatehpur"),
  d("Firozabad"),
  d("Gautam Buddha Nagar", "Noida", "Greater Noida"),
  d("Ghaziabad"),
  d("Ghazipur"),
  d("Gonda"),
  d("Gorakhpur"),
  d("Hamirpur"),
  d("Hapur"),
  d("Hardoi"),
  d("Hathras"),
  d("Jalaun", "Orai"),
  d("Jaunpur"),
  d("Jhansi"),
  d("Kannauj"),
  d("Kanpur Dehat", "Akbarpur Mati"),
  d("Kanpur Nagar", "Kanpur"),
  d("Kasganj"),
  d("Kaushambi", "Manjhanpur"),
  d("Lakhimpur Kheri", "Lakhimpur"),
  d("Kushinagar", "Padrauna"),
  d("Lalitpur"),
  d("Lucknow"),
  d("Maharajganj"),
  d("Mahoba"),
  d("Mainpuri"),
  d("Mathura"),
  d("Mau"),
  d("Meerut"),
  d("Mirzapur"),
  d("Moradabad"),
  d("Muzaffarnagar"),
  d("Pilibhit"),
  d("Pratapgarh"),
  d("Prayagraj", "Prayagraj"),
  d("Raebareli"),
  d("Rampur"),
  d("Saharanpur"),
  d("Sambhal", "Bahjoi"),
  d("Sant Kabir Nagar", "Khalilabad"),
  d("Shahjahanpur"),
  d("Shamli"),
  d("Shravasti", "Bhinga"),
  d("Siddharthnagar", "Navgarh"),
  d("Sitapur"),
  d("Sonbhadra", "Robertsganj"),
  d("Sultanpur"),
  d("Unnao"),
  d("Varanasi"),
]);
